name: Build and push Docker image ğŸ³

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: my-docker-image ğŸ–¼ï¸
  DOCKER_REGISTRY: my-container-registry.azurecr.io ğŸŒ
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }} ğŸ‘¤
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} ğŸ”’

jobs:
  build:
    runs-on: ubuntu-latest ğŸ§
    steps:
      - name: Checkout code ğŸ›’
        uses: actions/checkout@v2

      - name: Build Docker image ğŸ—ï¸
        run: docker build -t $IMAGE_NAME .

      - name: Login to Docker registry ğŸ”‘
        run: docker login $DOCKER_REGISTRY -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Push Docker image ğŸš€
        run: docker push $DOCKER_REGISTRY/$IMAGE_NAME

      - name: Send Notification to Slack ğŸ“©
        uses: rtCamp/action-slack-notify@v2
        env:
          # Specify the Slack channel to notify
          SLACK_CHANNEL: '#my-channel'
          # Set an emoji icon for the notification
          SLACK_ICON_EMOJI: ':rocket:'
          # Specify the username for the notification
          SLACK_USERNAME: 'GitHub Actions'
          # Set the message to include in the notification
          SLACK_MESSAGE: 'Docker image build and push successful!'
          # Use a secret to store the Slack webhook URL
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }} # Use a secret to store the Slack webhook URL for security purposes ğŸ¤«
