name: Automated Testing Workflow ğŸ¤–ğŸ§ª

on:
  workflow_call:
    inputs:
      python_version:
        description: 'Python version for the virtual environment'
        required: true
        default: '3.9'
      tests_folder:
        description: 'Location of the test folder'
        required: true
        default: 'tests'
      requirements_file:
        description: 'Path to requirements.txt file'
        required: true
        default: 'requirements.txt'

jobs:
  test:
    runs-on: ubuntu-latest ğŸ§
    name: Run Tests ğŸƒâ€â™‚ï¸ğŸƒâ€â™€ï¸
    steps:
      - uses: actions/checkout@v2 ğŸ›’
      - name: Set up Python ${{ inputs.python_version }} ğŸ
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python_version }}
      - name: Install dependencies ğŸ“¦
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ inputs.requirements_file }}
      - name: Run tests ğŸ§ª
        run: pytest ${inputs.tests_folder}
